Controllers/KonkursController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplikacjaHodowcy.Models;
using AplikacjaHodowcy.KonkursyFactory.Interfaces;
using AplikacjaHodowcy.KonkursyFactory;

namespace AplikacjaHodowcy.Controllers
{
    public class KonkursController : Controller
    {
        private readonly IKonkursFactory _konkursFactory;

        public KonkursController(IKonkursFactory konkursFactory)
        {
            _konkursFactory = konkursFactory;
        }

        public IActionResult Index()
        {
            List<Konkurs> konkursy = _konkursFactory.GetAllKonkursy();
            return View(konkursy);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var konkurs = new Konkurs();
            return View(konkurs);
        }

        [HttpPost]
        public IActionResult Create(Konkurs konkurs)
        {
            if (!ModelState.IsValid)
            {
                return View(konkurs);
            }

            if (konkurs.Type == "Krajowa")
            {
                var konkursF = _konkursFactory.CreateKrajowy(konkurs.Type, konkurs.Name, konkurs.Desription, konkurs.PhotoPath, konkurs.KrajoweRegulacje);
                _konkursFactory.Add(konkursF);
            }
            else if (konkurs.Type == "Miedzynarodowa")
            {
                var konkursF = _konkursFactory.CreateMiedzynarodowy(konkurs.Type, konkurs.Name, konkurs.Desription, konkurs.PhotoPath, konkurs.Kraj);
                var kMiedzynarodowy = konkursF as KonkursMiedzynarodowy;
                if (kMiedzynarodowy != null && !kMiedzynarodowy.CheckKraj())
                {
                    ModelState.AddModelError("PhotoPath", "Wybrany kraj nie jest dostepny");
                    return View(konkurs);
                }
                _konkursFactory.Add(konkursF);
            }
            else
            {
                return BadRequest("Nieznany typ konkursu.");
            }

            return RedirectToAction(nameof(Index));
        }


        //[HttpGet]
        //public IActionResult Create()
        //{
        //    Konkurs konkurs = new Konkurs();
        //    return View(konkurs);
        //}

        //[HttpPost]
        //public IActionResult Create(Konkurs konkurs)
        //{
        //    try
        //    {
        //        _konkursFactory.Add(konkurs);
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch (Exception ex)
        //    {
        //        ModelState.AddModelError(string.Empty, ex.InnerException.Message);
        //        return View(konkurs);
        //    }
        //}

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Konkurs konkurs = _konkursFactory.GetKonkurs(id);
            return View(konkurs);
        }

        [HttpPost]
        public IActionResult Edit(Konkurs konkurs)
        {
            try
            {
                _konkursFactory.Update(konkurs);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.InnerException.Message);
                return View(konkurs);
            }
        }

        [HttpGet]
        public IActionResult Details(int Id)
        {
            Konkurs konkurs = _konkursFactory.GetKonkurs(Id);
            return View(konkurs);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Konkurs konkurs = _konkursFactory.GetKonkurs(id);
            return View(konkurs);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Konkurs konkurs)
        {
            try
            {
                Konkurs existingKonkurs = _konkursFactory.GetKonkurs(konkurs.Id);
                _konkursFactory.Delete(existingKonkurs);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.InnerException.Message);
                return View(konkurs);
            }
        }
    }
}

Controllers/LiniaController.cs
using AplikacjaHodowcy.Data;
using AplikacjaHodowcy.Interfaces;
using AplikacjaHodowcy.Mappers;
using AplikacjaHodowcy.Models;
using AplikacjaHodowcy.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AplikacjaHodowcy.Controllers
{
    public class LiniaController : Controller
    {
        private readonly ILiniaRepository _liniaRepository;
        private readonly LiniaMapper _liniaMapper;

        public LiniaController(ILiniaRepository liniaRepository, LiniaMapper liniaMapper)
        {
            _liniaRepository = liniaRepository;
            _liniaMapper = liniaMapper;
        }

        public IActionResult Index()
        {
            List<Linia> linie = _liniaRepository.GetAllLinie().OrderBy(l => l.Name).ToList();
            IEnumerable<LiniaViewModel> linieViewModel = _liniaMapper.MapLinieToViewModels(linie);
            return View(linieViewModel);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            LiniaViewModel liniaViewModel = new LiniaViewModel();
            return View(liniaViewModel);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create(LiniaViewModel liniaViewModel)
        {
            try
            {
                _liniaRepository.Add(liniaViewModel);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.InnerException.Message);
                return View(liniaViewModel);
            }
            
        }

        [HttpGet]
        public IActionResult CreateModalForm()
       {
            LiniaViewModel liniaViewModel = new LiniaViewModel();
            return PartialView("_CreateModalForm", liniaViewModel);
        }

        [HttpPost]
        public IActionResult CreateModalForm(LiniaViewModel liniaViewModel)
        {
            _liniaRepository.Add(liniaViewModel);
            _liniaRepository.SaveChanges();
            return NoContent();
        }

        [HttpGet]
        public IActionResult Details(int Id)
        {
            Linia linia = _liniaRepository.GetLinia(Id);
            LiniaViewModel liniaViewModel = _liniaMapper.MapLinieToViewModels(new List<Linia> { linia }).FirstOrDefault();
            return View(liniaViewModel);
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Linia linia = _liniaRepository.GetLinia(Id);
            LiniaViewModel liniaViewModel = _liniaMapper.MapLinieToViewModels(new List<Linia> { linia }).FirstOrDefault();
            return View(liniaViewModel);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(LiniaViewModel liniaViewModel)
        {
            try 
            {
                _liniaRepository.Update(liniaViewModel);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex) 
            {
                ModelState.AddModelError(string.Empty, ex.InnerException.Message);
                return View(liniaViewModel);
            }
            
        }


        [HttpGet]
        public IActionResult Delete(int Id)
        {
            Linia linia = _liniaRepository.GetLinia(Id);
            LiniaViewModel liniaViewModel = _liniaMapper.MapLinieToViewModels(new List<Linia> { linia }).FirstOrDefault();
            return View(liniaViewModel);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Delete(LiniaViewModel liniaViewModel)
        {
            try
            {
                Linia exisistingLinia = _liniaRepository.GetLinia(liniaViewModel.Id);
                _liniaRepository.Delete(exisistingLinia);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.InnerException.Message);
                return View(liniaViewModel);
            }    
        }

        //public JsonResult GetLinie()
        //{
        //    var listaLinii = new List<SelectListItem>();
        //    List<Linia> Linie = _liniaRepository.GetAllLinie();

        //    listaLinii = Linie.Select(l => new SelectListItem()
        //    {
        //        Value = l.Id.ToString(),
        //        Text = l.Nazwa
        //    }).ToList();

        //    var defItem = new SelectListItem()
        //    {
        //        Value = "",
        //        Text = "----Wybierz Linię----"
        //    };

        //    listaLinii.Insert(0, defItem);

        //    return Json(listaLinii);
        //}
    }
}

Controllers/MiotController.cs
using AplikacjaHodowcy.Models;
using AplikacjaHodowcy.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using AplikacjaHodowcy.Repositories;
using AplikacjaHodowcy.Mappers;
using AplikacjaHodowcy.ViewModels;
using AplikacjaHodowcy.Interfaces;

namespace Hodowla.Controllers
{
    public class MiotController : Controller
    {
        private readonly IMiotRepository _miotRepository;
        private readonly MiotMapper _miotMapper;
        private readonly IMiotService _miotService;

        public MiotController(IMiotRepository miotRepository, MiotMapper miotMapper, IMiotService miotService)
        {
            _miotRepository = miotRepository;
            _miotMapper = miotMapper;
            _miotService = miotService;
        }

        public IActionResult Index()
        {
            List<Miot> mioty = _miotRepository.GetWithLinia().OrderBy(x => x.LitterName).ToList();
            IEnumerable<MiotViewModel> miotyViewModel = _miotMapper.MapMiotToViewModel(mioty);
            return View(miotyViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Linie = _miotService.GetLinie();
            return View(new MiotViewModel());
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create(MiotViewModel miotViewModel)
        {
            if (ModelState.IsValid)
            {
                _miotRepository.Add(miotViewModel);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Linie = _miotService.GetLinie();
            return View(miotViewModel);

        }

        [HttpGet]
        public IActionResult Details(int Id)
        {
            Miot miot = _miotRepository.GetById(Id);

            if (miot == null)
            {
                return NotFound();
            }

            MiotViewModel miotViewModel = _miotMapper.MapMiotToViewModel(new List<Miot> { miot }).FirstOrDefault(); // Mapuj pojedynczy obiekt Miot
            ViewBag.Linie = _miotService.GetLinie();
            return View(miotViewModel);
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Miot miot = _miotRepository.GetById(Id);

            if (miot == null)
            {
                return NotFound();
            }

            MiotViewModel miotViewModel = _miotMapper.MapMiotToViewModel(new List<Miot> { miot }).FirstOrDefault(); // Mapuj pojedynczy obiekt Miot
            ViewBag.Linie = _miotService.GetLinie();
            return View(miotViewModel);
        }


        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(MiotViewModel miotViewModel)
        {
            if (ModelState.IsValid)
            {
                Miot miot = _miotMapper.MapViewModelToMiot(miotViewModel);
                _miotRepository.Update(miot);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Linie = _miotService.GetLinie();
            return View(miotViewModel);
        }


        [HttpGet]
        public IActionResult Delete(int Id)
        {
            Miot miot = _miotRepository.GetById(Id);
            if (miot == null)
            {
                return NotFound();
            }

            MiotViewModel miotViewModel = _miotMapper.MapMiotToViewModel(new List<Miot> { miot }).FirstOrDefault();
            return View(miotViewModel);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Delete(Miot Miot)
        {
                _miotRepository.Delete(Miot);
                return RedirectToAction(nameof(Index));
        }


    }
}

Views/Shared/_CreateModalDialog.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div id="DivCreateDialogHolder" class="modal fade text-width:30%;"
    role="dialog">

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h2>Create</h2>
            <button type="button" class="close" data-bs-dismiss="modal">&times;</button>
        </div>
        <div id="DivCreateDialog" class="modal-body">
        </div>

        <div class="modal-footer">
            @*<button type="button" class="btn btn-secondary" data-icon="Close" data-bs-dismiss="modal">Close</button>*@

            <div class="btn-group">
                <div>
                    <button id="dupBackBtn" type="button" class="btn btn-danger" data-icon="back" data-bs-dismiss="modal">Back</button>
                    </div>
                    <div class="ml-4">
                        <input id="dupSubmitBtn" type="button" value="Save" class="btn btn-primary"
                        onclick="submitModalForm()"/>
                        </div>
                        </div>
        </div>
    </div>
  </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Frosty Paws Nest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplikacjaHodowcy.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="/css/mainLayout.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"> </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"> </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light navbar-custom border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Frosty Paws Nest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Strona Główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Linia" asp-action="Index">Linie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Miot" asp-action="Index">Mioty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Szczeniak" asp-action="Index">Szczeniaki</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Konkurs" asp-action="Index">Wystawy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Kontakt</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                            <img src="/images/lapa.png" alt="Lapa" class="small-image"> 

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            <partial name="_CreateModalDialog" />

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="color: lightgray">
            &copy; 2024 - Frosty Paws Nest -
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Kontakt</a>
            <a href="https://www.facebook.com/" target="_blank" style="float: right; margin-left: 10px;"><img src="/images/facebook.png" alt="Facebook" style="width: 30px; height: 30px;"></a>
            <a href="https://www.instagram.com/" target="_blank" style="float: right;"><img src="/images/instagram.png" alt="Instagram" style="width: 30px; height: 30px;"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>